import type { CatalogProduct, ProductCategory } from "./catalog";

export const officialCatalogProducts: CatalogProduct[] = [
  {
    id: "gs-1",
    name: "Wireless charger",
    priceGHS: 120,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "home",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.6,
    reviewCount: 61,
    imageCount: 4,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
    warranty: "12 months",
  },
  {
    id: "gs-2",
    name: "Floral wrap dress",
    priceGHS: 180,
    originalPriceGHS: 220,
    discountPercent: 18,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "fashion",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.7,
    reviewCount: 89,
    imageCount: 4,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
  },
  {
    id: "gs-3",
    name: "Pro wireless earbuds",
    priceGHS: 220,
    originalPriceGHS: 260,
    discountPercent: 15,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "phones",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.5,
    reviewCount: 98,
    imageCount: 4,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
    warranty: "12 months",
  },
  {
    id: "gs-4",
    name: "Rose glow skincare set",
    priceGHS: 150,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "beauty",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.6,
    reviewCount: 61,
    imageCount: 4,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
  },
];

export function getOfficialProductById(id: string): CatalogProduct | undefined {
  return officialCatalogProducts.find((p) => p.id === id);
}

export function getOfficialProductsByCategory(category: ProductCategory): CatalogProduct[] {
  return officialCatalogProducts.filter((p) => p.category === category);
}
