import type { CatalogProduct, ProductCategory } from "./catalog";

export const officialCatalogProducts: CatalogProduct[] = [
  {
    id: "gs-1",
    name: "Wireless charger",
    priceGHS: 120,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "electronics",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.6,
    reviewCount: 61,
    imageCount: 4,
    videoSlideIndex: 1,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
    warranty: "12 months",
    description:
      "15W fast wireless charger compatible with all Qi-enabled phones. Slim, non-slip base with an LED charge indicator that dims automatically at night.\n\nOver-charge and over-heat protection built in, so it's safe to leave charging overnight.",
    specs: [
      { label: "Output", value: "15W max (Qi-compatible)" },
      { label: "Input", value: "USB-C" },
      { label: "Compatibility", value: "All Qi-enabled phones" },
    ],
    boxContents: ["1 × Wireless charger", "1 × USB-C cable"],
    stockCount: 42,
    colorVariants: [
      { label: "Black", hex: "#1A1A1A" },
      { label: "White", hex: "#F5F5F5" },
    ],
  },
  {
    id: "gs-2",
    name: "Floral wrap dress",
    priceGHS: 180,
    originalPriceGHS: 220,
    discountPercent: 18,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "women",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.7,
    reviewCount: 89,
    imageCount: 4,
    videoSlideIndex: 0,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
    description:
      "A soft floral wrap dress with a flattering waist tie and flowy midi length. Lightweight fabric, perfect for warm-weather days and evening outings alike.\n\nAdjustable wrap tie fits a range of body shapes comfortably.",
    specs: [
      { label: "Material", value: "Polyester crepe" },
      { label: "Fit", value: "Wrap style, adjustable tie" },
      { label: "Available sizes", value: "XS – XL" },
      { label: "Care", value: "Machine wash cold, gentle cycle" },
    ],
    boxContents: ["1 × Wrap dress"],
    stockCount: 19,
    colorVariants: [
      { label: "Pink floral", hex: "#E8A0BF" },
      { label: "Blue floral", hex: "#A0C4E8" },
      { label: "Cream floral", hex: "#EFE6D8" },
    ],
  },
  {
    id: "gs-3",
    name: "Pro wireless earbuds",
    priceGHS: 220,
    originalPriceGHS: 260,
    discountPercent: 15,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "electronics",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.5,
    reviewCount: 98,
    imageCount: 4,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
    warranty: "12 months",
    description:
      "Premium true wireless earbuds with active noise cancellation, 30-hour total battery life, and a low-latency gaming mode. Touch controls and multi-point Bluetooth pairing to switch between two devices instantly.\n\nBacked by GRAPPlive's own 12-month warranty — genuine product, guaranteed.",
    specs: [
      { label: "Bluetooth version", value: "5.3" },
      { label: "Battery life", value: "8 hrs (buds) / 30 hrs (with case)" },
      { label: "Noise cancellation", value: "Active (ANC)" },
      { label: "Water resistance", value: "IPX5" },
    ],
    boxContents: ["2 × Earbuds", "1 × Charging case", "1 × USB-C cable", "2 × Extra ear tip sizes"],
    stockCount: 33,
    colorVariants: [
      { label: "Midnight black", hex: "#1A1A1A" },
      { label: "Pearl white", hex: "#F5F5F5" },
    ],
  },
  {
    id: "gs-4",
    name: "Rose glow skincare set",
    priceGHS: 150,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "beauty",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.6,
    reviewCount: 61,
    imageCount: 4,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
    description:
      "A 3-step rose-infused skincare set — cleanser, toner, and moisturizer — formulated for daily glow. Free from parabens and sulfates, suitable for all skin types.\n\nGenuine, sealed product sourced and sold directly by GRAPPlive.",
    specs: [
      { label: "Set includes", value: "Cleanser, toner, moisturizer" },
      { label: "Skin type", value: "All skin types" },
      { label: "Free from", value: "Parabens, sulfates" },
    ],
    boxContents: ["1 × Cleanser (150ml)", "1 × Toner (150ml)", "1 × Moisturizer (50ml)"],
    stockCount: 21,
  },
  {
    id: "gs-5",
    name: "Men's slim-fit denim jacket",
    priceGHS: 210,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "men",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.6,
    reviewCount: 54,
    imageCount: 4,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
    description:
      "A classic slim-fit denim jacket in a mid-wash blue, built for everyday layering. Sturdy cotton denim that softens with wear, with a timeless collar and button front.\n\nPairs easily with almost anything — a wardrobe staple, not a trend piece.",
    specs: [
      { label: "Material", value: "100% cotton denim" },
      { label: "Fit", value: "Slim, true to size" },
      { label: "Available sizes", value: "S – XXL" },
      { label: "Care", value: "Machine wash cold, inside out" },
    ],
    boxContents: ["1 × Denim jacket"],
    stockCount: 26,
    colorVariants: [
      { label: "Mid-wash blue", hex: "#5B7FA6" },
      { label: "Dark indigo", hex: "#2C3E5C" },
    ],
  },
  {
    id: "gs-6",
    name: "Kids' cotton playset (2-piece)",
    priceGHS: 95,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "children",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.8,
    reviewCount: 37,
    imageCount: 4,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
    description:
      "A soft, breathable 2-piece cotton set for everyday play — a comfortable top paired with matching shorts, built to survive a full day of running around.\n\nEasy-care fabric that holds up to frequent washing without losing shape or color.",
    specs: [
      { label: "Material", value: "100% cotton" },
      { label: "Set includes", value: "Top and shorts" },
      { label: "Available sizes", value: "2–8 years" },
      { label: "Care", value: "Machine washable" },
    ],
    boxContents: ["1 × Top", "1 × Shorts"],
    stockCount: 31,
    colorVariants: [
      { label: "Sky blue", hex: "#A8CBE8" },
      { label: "Sunshine yellow", hex: "#F0D878" },
    ],
  },
  {
    id: "gs-7",
    name: "Leather tote bag",
    priceGHS: 175,
    originalPriceGHS: 210,
    discountPercent: 17,
    sellerId: "grapplive-official",
    sellerName: "GrappStore",
    sellerOrdersCompleted: 0,
    sellerReplyTime: "",
    origin: "grapp_import",
    category: "accessories",
    sellerSocials: {},
    verifiedTier: null,
    sourceType: "grapplive",
    rating: 4.7,
    reviewCount: 42,
    imageCount: 4,
    deliveryEstimate: "3–5 days, GRAPPlive guaranteed",
    returnPolicyDays: 7,
    description:
      "A structured tote in genuine leather, roomy enough for daily essentials with a secure top zip. Sturdy handles built for everyday carry, from the office to the market.\n\nAges well with use — genuine leather develops character over time.",
    specs: [
      { label: "Material", value: "Genuine leather" },
      { label: "Closure", value: "Top zip" },
      { label: "Interior", value: "1 zip pocket, 2 slip pockets" },
    ],
    boxContents: ["1 × Tote bag"],
    stockCount: 15,
    colorVariants: [
      { label: "Tan", hex: "#C89B6B" },
      { label: "Black", hex: "#1A1A1A" },
    ],
  },
];

export function getOfficialProductById(id: string): CatalogProduct | undefined {
  return officialCatalogProducts.find((p) => p.id === id);
}

export function getOfficialProductsByCategory(category: ProductCategory): CatalogProduct[] {
  return officialCatalogProducts.filter((p) => p.category === category);
}
